<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Creating Promises!</title>
</head>
<body>
<script>
/*The Promise(resolver) contructor is used to create promises. The resolver is
a method that takes 2 arguments: resolve & reject. If the promise is successful,
then the resolve method is called.  If it fails, then the reject method is called.
In Wes's example below, he created a promise that is set to fail after 1 second hence
causing the reject method to fire. The error message generated by the reject method
is then picked up by the .catch handler and logged to the console.

If the Promise had been successful, then a resolve method would have fired and then
the result of the successful Promise would have been picked up by the .then handler.*/
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(Error('Err wes isn\'t cool'));
    }, 1000);
  });

  p
    .then(data => {
      console.log(data);
    })
    .catch(err => {
      console.error(err);
    });

//Another example:
function randomNum() {
  return new Promise((resolve,reject) => {
    var num = Math.floor((Math.random()*10)+1)
    if(num >= 5) {
      resolve(num);
    } else {
      reject(num);
    }
  })
};

randomNum()
.then(num => num)
.then(num => {
  console.log(`Success! Your number is ${num}.`);
})
.catch(num => {
  console.log(`Failed! Your number ${num} is less than 5.`);
});

</script>
</body>
</html>
